### ISSUE TITLE
Panic when quickly move the grids

### ISSUE THREAD

**Issue by tannineo** [tannineo/2048-cli#1]
```
panic: crypto/rand: argument to Int is <= 0

goroutine 1 [running]:
crypto/rand.Int(0x115e1a0, 0xc42007a1b0, 0xc420047d80, 0x100b02a, 0x10c1e20, 0xc420097eb4)
        /usr/local/Cellar/go/1.9.2/libexec/src/crypto/rand/util.go:108 +0x30e
github.com/tannineo/2048-cli/gameplate.(*Grid44).GenerateNewCells(0xc42001e090, 0x2)
        /Users/carychan/Code/go/src/github.com/tannineo/2048-cli/gameplate/grid44.go:254 +0x1f6
main.main()
        /Users/carychan/Code/go/src/github.com/tannineo/2048-cli/main.go:68 +0x48c
exit status 2
```

**Comment by tannineo** [comment]
不是按太快了, 循环边界错误, 少算了格子, 导致空格为0, 报错
